WMS\EstoqueBundle\Entity\Item:
    type: entity
    table: item
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        item_number:
            type: integer
            length: 3
            unique: true
        created_at:
            type: datetime
        updated_at:
            type: datetime
            nullable: true
        cost:
            type: decimal
        discount:
            type: decimal
        
        
        
    manyToOne:
        PurchaseOrder:
            targetEntity: PurchaseOrder
            inversedBy: itens
            joinColumn:
                name: purchase_order_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]    
    